apiVersion: v1
data:
  cert: {{ .Values.elasticCert }}
  password: {{ .Values.elasticPassword | b64enc | quote }}
kind: Secret
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
type: Opaque
