apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: 9200-tcp
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: 9300-tcp
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector: 
    app: {{ .Values.appName }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}-external
spec:
  ports:
  - name: 9200-tcp
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: 9300-tcp
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: {{ .Values.appName }}
